### PR TITLE
Jenkins use multiconfig web page validation

### PR DESCRIPTION
**Pull request by ebecheva**
Changes have been made in scripts/writeToFile.py and Jenkinsfile.
This script and Jenkinsfile are to use with one configuration.
Two directories are created : PR# and PR#/PR#config1. Pictures with histograms are copied to PR#/PR#config1. The txt file containing the information to be written on the web page is in the file PR#/validation_webpages.txt

PR#/
PR#/validation_webpages.txt
PR#/PR#config1

### CODE REVIEW

**Comment by jbsauvan** [comment]
Is there a test webpage that as been produced from one PR? To check that it works as expected before merging?

**Comment by ebecheva** [comment]
You can see PR43 in the test validation web page https://test.llrhgcaltpgvalidation.in2p3.fr/

**Comment by jbsauvan** [comment]
Thanks
Regarding the left menu, it would be better to display only the config name instead of repeating the PR information [1], which is already written at the top of the page. In that case, only "config1" would be displayed.

[1] 
image

**Comment by ebecheva** [comment]
Validation test for Config1 title => https://test.llrhgcaltpgvalidation.in2p3.fr/list_config.php?pr=PR43

**Pull request merged**
